@startuml

title __SP's Class Diagram__\n

  namespace com.example.appkru {
    namespace model.SP {
      class com.example.appkru.model.SP.DatumSP {
          - dinasId : String
          - kelas : String
          - kode : String
          - mesin : String
          - nama : String
          - namaPengatur : String
          - nipNama : String
          - nipNamaMengganti : String
          - nopol : String
          - posisi : String
          - posisiPengatur : String
          - tanggalPanjang : String
          - tanggalPendek : String
          - trayek : String
          + getDinasId()
          + getKelas()
          + getKode()
          + getMesin()
          + getNama()
          + getNamaPengatur()
          + getNipNama()
          + getNipNamaMengganti()
          + getNopol()
          + getPosisi()
          + getPosisiPengatur()
          + getTanggalPanjang()
          + getTanggalPendek()
          + getTrayek()
          + setDinasId()
          + setKelas()
          + setKode()
          + setMesin()
          + setNama()
          + setNamaPengatur()
          + setNipNama()
          + setNipNamaMengganti()
          + setNopol()
          + setPosisi()
          + setPosisiPengatur()
          + setTanggalPanjang()
          + setTanggalPendek()
          + setTrayek()
      }
    }
  }
  

  namespace com.example.appkru {
    namespace model.SP {
      class com.example.appkru.model.SP.SP {
          - data : List<DatumSP>
          - status : Boolean
          + getData()
          + getStatus()
          + setData()
          + setStatus()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
