@startuml

title __LAPORANKONTROL's Class Diagram__\n

  namespace com.example.appkru {
    namespace model.LaporanKontrol {
      class com.example.appkru.model.LaporanKontrol.DatumLaporanKontrol {
          - id : String
          - jenisPelanggaran : String
          - jumlahPenumpang : String
          - kelas : String
          - keterangan : String
          - laporanHarianId : String
          - naikKontrol : String
          - nama : String
          - nopol : String
          - pendapatanKontrol : String
          - tanggalNaikKontrol : String
          - tanggalTurunKontrol : String
          - trayek : String
          - turunKontrol : String
          + getId()
          + getJenisPelanggaran()
          + getJumlahPenumpang()
          + getKelas()
          + getKeterangan()
          + getLaporanHarianId()
          + getNaikKontrol()
          + getNama()
          + getNopol()
          + getPendapatanKontrol()
          + getTanggalNaikKontrol()
          + getTanggalTurunKontrol()
          + getTrayek()
          + getTurunKontrol()
          + setId()
          + setJenisPelanggaran()
          + setJumlahPenumpang()
          + setKelas()
          + setKeterangan()
          + setLaporanHarianId()
          + setNaikKontrol()
          + setNama()
          + setNopol()
          + setPendapatanKontrol()
          + setTanggalNaikKontrol()
          + setTanggalTurunKontrol()
          + setTrayek()
          + setTurunKontrol()
      }
    }
  }
  

  namespace com.example.appkru {
    namespace model.LaporanKontrol {
      class com.example.appkru.model.LaporanKontrol.LaporanKontrol {
          - data : List<DatumLaporanKontrol>
          - status : Boolean
          + getData()
          + getStatus()
          + setData()
          + setStatus()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
