@startuml

title __BUKTISETORAN's Class Diagram__\n

  namespace com.example.appkru {
    namespace model.BuktiSetoran {
      class com.example.appkru.model.BuktiSetoran.BuktiSetoran {
          - data : List<DatumBuktiSetoran>
          - status : Boolean
          + getData()
          + getStatus()
          + setData()
          + setStatus()
      }
    }
  }
  

  namespace com.example.appkru {
    namespace model.BuktiSetoran {
      class com.example.appkru.model.BuktiSetoran.DaftarPengeluaran {
          - namaPengeluaran : String
          - nominal : String
          + getNamaPengeluaran()
          + getNominal()
          + setNamaPengeluaran()
          + setNominal()
      }
    }
  }
  

  namespace com.example.appkru {
    namespace model.BuktiSetoran {
      class com.example.appkru.model.BuktiSetoran.DatumBuktiSetoran {
          - daftarPengeluaran : List<DaftarPengeluaran>
          - jumlahPremi : String
          - kelas : String
          - namaKernet : String
          - namaKondektur : String
          - namaSopir : String
          - nipNamaKernet : String
          - nipNamaKondektur : String
          - nipNamaSopir : String
          - nopol : String
          - pendapatanRit : String
          - pengeluaran : String
          - premiKernet : String
          - premiKondektur : String
          - premiSopir : String
          - setoranKasAngka : String
          - setoranKasTerbilang : String
          - sisaPendapatan : String
          - statusSelesai : String
          - trayek : String
          - waktuBerangkat : String
          + getDaftarPengeluaran()
          + getJumlahPremi()
          + getKelas()
          + getNamaKernet()
          + getNamaKondektur()
          + getNamaSopir()
          + getNipNamaKernet()
          + getNipNamaKondektur()
          + getNipNamaSopir()
          + getNopol()
          + getPendapatanRit()
          + getPengeluaran()
          + getPremiKernet()
          + getPremiKondektur()
          + getPremiSopir()
          + getSetoranKasAngka()
          + getSetoranKasTerbilang()
          + getSisaPendapatan()
          + getStatusSelesai()
          + getTrayek()
          + getWaktuBerangkat()
          + setDaftarPengeluaran()
          + setJumlahPremi()
          + setKelas()
          + setNamaKernet()
          + setNamaKondektur()
          + setNamaSopir()
          + setNipNamaKernet()
          + setNipNamaKondektur()
          + setNipNamaSopir()
          + setNopol()
          + setPendapatanRit()
          + setPengeluaran()
          + setPremiKernet()
          + setPremiKondektur()
          + setPremiSopir()
          + setSetoranKasAngka()
          + setSetoranKasTerbilang()
          + setSisaPendapatan()
          + setStatusSelesai()
          + setTrayek()
          + setWaktuBerangkat()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
